site_name: '@rmp135/imgur'
theme: readthedocs
pages:
  - 'index.md'
  - 'authorization.md'
  - API:
    - 'api/account.md'
    - 'api/comment.md'
    - 'api/conversation.md'
    - Custom Gallery: 'api/customgallery.md'
    - 'api/gallery.md'
    - 'api/image.md'
  - 'uploading.md'
  - Rate Limits: 'ratelimits.md'
  - Error Handling: 'errors.md'
  - 'contributing.md'
  - 'typescript.md'